version: "3.9"

services:
  mysql:
    image: mysql:8.0.25
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_GRADER_USER}
      MYSQL_PASSWORD: ${DB_GRADER_PASSWORD}
    volumes:
      - ./database:/var/lib/mysql