name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linter:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install poetry
        run: pipx install poetry==1.2.2

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: poetry

      - name: Install environment
        run: poetry install --only dev

      - name: Log in with sourcery
        run: sourcery login --token ${{ secrets.SOURCERY_TOKEN }}

      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.0

  test:
    matrix:
      os: [ ubuntu-20.04, windows-2022, macos-12 ]
      python: [ "3.10" ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install poetry
        run: pipx install poetry==1.2.2

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: poetry

      - name: Install environment
        run: poetry install --with dev

      - name: Run tests
        run: pytest
